name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SHOW_TITLE: true
          TIME_RANGE: last_year
          SHOW_TOTAL: true
          SHOW_TIME: true
          LANG_COUNT: 8
          BLOCKS: "░▒▓█"
          CODE_LANG: markdown
          IGNORED_LANGUAGES: "JSON YAML"

          COMMIT_MESSAGE: "Updated coding stats 📊"
          TARGET_BRANCH: main
          COMMITTER_NAME: github-actions[bot]
          COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
